return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "html",
      "javascript",
      "json",
      "lua",
      "markdown",
      "markdown_inline",
      "python",
      "tsx",
      "typescript",
      "vim",
      "svelte",
      "css",
      "scss",
      "c_sharp",
      "comment",
      "jsdoc",
      "graphql",
    },
  },
}
